MODULE := "example_gitlab"
EXE := $(MODULE)
include ../../../make/globals.mk

all:
	$(call not-supported-msg,$(MODULE))

clean:
	$(call not-supported-msg,$(MODULE))

build: go_build

deps:
	$(call not-supported-msg,$(MODULE))

fmt:
	$(call not-supported-msg,$(MODULE))

test:
	$(call not-supported-msg,$(MODULE))

run:
	$(call not-supported-msg,$(MODULE))
