name: Setup Go Environment
description: 'Sets up a go environment'

runs:
  using: composite
  steps:
    - name: Set up Go 1.8
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Setup protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - name: Go Build Cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.go-cache-paths.outputs.go-build }}
           ~/.cache/go-build
           ~/go/pkg/mod
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
