DESTDIR := ../build
MODULE := "receptor_sdk"
include ../../make/globals.mk

all:
	$(call not-supported-msg,$(MODULE))

clean:
	$(call not-supported-msg,$(MODULE))

build:
	$(call not-supported-msg,$(MODULE))

deps:
	$(call not-supported-msg,$(MODULE))

fmt:
	$(call not-supported-msg,$(MODULE))

test:
	$(call not-supported-msg,$(MODULE))

run:
	$(call not-supported-msg,$(MODULE))
