name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - release-candidate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Build
        run: |
          make all

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Test
        run: |
          make deps test

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Check Formatting
        run: |
          make lint
        working-directory: go

  python-build-and-test:
    name: "Python Build and Test"
    secrets: inherit
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # we need this so that tags are pulled; unfortunately it also pulls all history
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
      - name: Setup Poetry
        uses: pronovic/setup-poetry@v1
        with:
          version: "${{ inputs.poetry-version }}"
          plugins: "poetry-dynamic-versioning[plugin]:0.22.0,${{ inputs.poetry-plugins }}"
          cache-venv: "${{ inputs.poetry-cache-venv }}"
          cache-poetry: "${{ inputs.poetry-cache-install }}"
          cache-suffix: "001"  # safest to bump this when upgrading plugin above
      - name: Install dependencies
        working-directory: python
        run: |
          # Install dependencies
          poetry install --sync --no-interaction
      - name: Run test suite
        working-directory: python
        run: |
          ./run suite
      
    
