name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - release-candidate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Build
        run: |
          make all

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Test
        run: |
          make deps test

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Check Formatting
        run: |
          make lint
        working-directory: go

  python-build-and-test:
    name: "Python Build and Test"
    uses: pronovic/gha-shared-workflows/.github/workflows/poetry-build-and-test.yml@v3
    working-directory: python
    secrets: inherit
    with:
      matrix-os-version: "[ 'ubuntu-latest' ]"
      matrix-python-version: "[ '3.9', '3.10', '3.11' ]"  # run Linux tests on all supported Python versions
      poetry-version: "1.3.1"
      enable-coveralls: true  # only report to coveralls.io for tests that run on Linux

  python-release:
    name: "Python Release"
    if: github.ref_type == 'tag'
    uses: pronovic/gha-shared-workflows/.github/workflows/poetry-release.yml@v3
    needs: [ linux-build-and-test, macos-build-and-test, windows-build-and-test ]
    working-directory: python
    secrets: inherit
    with:
      python-version: "3.9"
      poetry-version: "1.3.1"
      publish-pypi: true